#!/bin/bash

makefile=$1

inotifywait -s -e close_write -m . --format %f | while read line;  do
	echo "$line updated..."
	make -f $makefile $(cat $makefile | grep -E "^.*: .*$line" | tr -d ':' |awk '{print $1}')
done

